### ISSUE TITLE
Help me set up Carnivores 2

### ISSUE THREAD

**Issue by LinuxBeaver** [lonyelon/carnivores-flake#1]
This is hype as I haven't played this game  since 2017 when I was on Windows 10. 

I installed Nix on Fedora 40 

I get this error though 

```
error: builder for '/nix/store/sdlrd0jcsv3a8wzpmcmpwxpdh00i9ngm-source.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://d1.myabandonware.com/t/2b28582f-ebc8-413c-ab73-7ea37eea6e7a/Carnivores-2_Win_EN_ISO-Version.zip
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 498
       > error: cannot download source from any mirror
       For full logs, run 'nix log /nix/store/sdlrd0jcsv3a8wzpmcmpwxpdh00i9ngm-source.drv'.
error: 1 dependencies of derivation '/nix/store/yv448674h355df4zdh57i7sgncvhr1pd-Carn2-1.0.0.drv' failed to build

```

**Comment by lonyelon** [comment]
This is bad since it means that the download link that the flake was using was temporal, and now the flake is unusable for anyone that does not have it cached. Let me try to switch to another host and try again.

Thanks for the report!

**Comment by lonyelon** [comment]
Latest commit fixes Carnivores 2 and IceAge. Carnivores 1 is not working yet because I can't find an Iso for it : (

**Comment by LinuxBeaver** [comment]
The audio isn't working (software stereo) and how do I get it to use direct3d/3dfx so the dinosaurs bleed and it snows?

You know that right? The snow in iceage and dinosaur/animal bleeding is dependent on 3dfx/direct 3d.

**Comment by LinuxBeaver** [comment]
I confirmed other apps work with audio on wine, also why do I have to use root?  I never used root wine for anything but this.

**Comment by lonyelon** [comment]
I have fixed the sources for all games now, they should work as long as the internet archive hosts those files.

Direct3d/3dfx do not work. I have tried but can't.

Root? to run the flake you do not need root. Can you be more specific? We can take this conversation to email if you want (sergio@lony.xyz).
